### ISSUE TITLE
Another default window size issue thing *sigh*

### ISSUE THREAD

**Issue by JjTheHusky** [SteffenL/dise#20]
The inventory tab has a lot of things crammed together due to the small default window size.

Most notably, the user's inventory is very small, barely shows the item name and doesn't show the rest of the items information without expanding it, while Jin's storage has all the space.
Also, the modify item box at the bottom runs out of room.
![dise_J4KhNBStqZ](https://user-images.githubusercontent.com/25309518/59149310-7ed04e00-89d9-11e9-8bec-7e9fb1e8b924.png)

By making the window size a little bigger, and giving equal space to both storage boxes, this can eliminate both issues, you can even give the name tab more space as well.
![dise_RsymNKZaHS](https://user-images.githubusercontent.com/25309518/59149329-c656da00-89d9-11e9-8db7-0435af30a246.png)

Lastly, while not a huge issue, the skills tab does hide a few skills, but resizing the window like before can fix the issue. (Image below is shown before window size change)
![dise_7AnGPq263r](https://user-images.githubusercontent.com/25309518/59149336-e9818980-89d9-11e9-913f-e0d1dc5f63d9.png)

Changing the default window size for the whole application should fix these issues.

**Comment by SteffenL** [comment]
Thanks for reporting this!

**Comment by SteffenL** [comment]
Increased the default window size to 1280x720. The problem with partially hidden skills is reduced with the new window size. The remaining problems with some skill trees is a problem for another day because it cannot be easily fixed with window size adjustments.

![image](https://user-images.githubusercontent.com/1543854/59162760-f6e06600-8af6-11e9-89a1-d856261ddbc2.png)

![image](https://user-images.githubusercontent.com/1543854/59162764-137c9e00-8af7-11e9-9d99-d22f7ecfae33.png)

![image](https://user-images.githubusercontent.com/1543854/59162766-1a0b1580-8af7-11e9-8aef-f05fe5996cd0.png)
