### ISSUE TITLE
Editor does not automatically show Definitive Edition saves

### ISSUE THREAD

**Issue by JjTheHusky** [SteffenL/dise#7]
The editor does not show the definitive edition saves on the home page list. The user must open and find the file manually.

Here is the save location for DE by steam default installation location: C:\Program Files (x86)\Steam\userdata\STEAMIDorsomething\383150\remote\out

**Comment by SteffenL** [comment]
Thanks for opening this issue!

DISE must support multiple save directories now. It does not currently detect the location (for Definitive Edition) automatically out of the box, but it has Steam integration so that it can be done without too much effort.

As a workaround for Steam, one can set the Steam app IDs and game storage location in the preferences dialog. Press "<" while Steam is running to get the location from Steam after setting the app IDs.

Here are the app IDs for Definitive Edition:

| App ID  | Game                      |
| -------- | -------------------- |
| 383150 | Dead Island             |
| 383180 | Dead Island: Riptide |

**Comment by JjTheHusky** [comment]
This fixes the issue for now until DISE can support both at the same time, thanks.

**Comment by SteffenL** [comment]
The latest experimental build of DISE adds support for showing Definitive Edition saves.
